title: "<Use a descriptive title here> "
body:
  - type: checkboxes
    attributes:
      label: Check these boxes if you have followed the posting rules.
      options:
        - label: Q&A Getting Started is the most appropriate category for my question (trouble installing, beginner user, ...)
          required: true
        - label: I have consulted the posting Guidelines on the Discussions front page
          required: true
        - label: I have searched the Discussions forum and my question has not been asked before
          required: true
        - label: I have searched the [MOOSE website](https://mooseframework.inl.gov) and the documentation does not answer my question
          required: true
        - label: I have formatted my post following the [posting guidelines](https://github.com/idaholab/moose/discussions/18270) (avoid screenshots if possible, triple back quotes before/after pasted text, etc)
          required: true
  - type: textarea
    id: question
    attributes:
      label: Issue or question about MOOSE
      description: Please give as much context as you think we could need
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Optional: Relevant error output
      description: Please copy and paste any relevant output
      placeholder: optionally paste errors here
      render: shell
  - type: textarea
    id: diagnostic
    attributes:
      label: Optional: Relevant diagnostic output
      description: Please copy and paste the output from executing `moose/scripts/diagnostics.sh`
      placeholder: optionally include output from running ./diagnostics.sh
      render: pre
