name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  precheck:
    if: github.repository == 'milljm/action_testing'
    runs-on: self-hosted
    env:
      MOOSE_JOBS: 6
    steps:
      - uses: actions/checkout@v4
      - name: Build MOOSE
        working-directory: ./test
        run: make -j ${MOOSE_JOBS}
      - name: Test MOOSE
        working-directory: ./test
        run: ./run_tests -j ${MOOSE_JOBS}
